#REQUIRED VARIABLES 
variable "dataset_id" {
  description = "A unique ID for this dataset, without the project name"
  type        = string
  default     = "dataset_id01"
}
variable "project_id" {
  description = "The ID of the project in which the resource belongs"
  type        = string
}
variable "description" {
  description = "A user-friendly description of the dataset"
  type        = string
  default     = "An optional description for this resource"
}
variable "location" {
  description = "The geographic location where the dataset should reside"
  type        = string
  default     = "asia-south1"
}
variable "user_by_email" {
  description = "An email address of a user to grant access to"
  type        = string
  default     = null
}


variable "labels" {
  description = "The labels associated with this dataset"
  type        = map(string)
  default     = null
}

variable "group_by_email" {
  description = "An email address of a Google Group to grant access to"
  type        = string
  default     = "DevOps@mahindra.com"
}

variable "policy_data" {
  description = "The policy data generated by a google_iam_policy data source."
  type        = string
  default     = null
}

variable "region" {
  description = "Available region for this resource"
  type        = string
  default     = "asia-south1"
}

/*
variable "kms_key_name" {
  description = "Describes the Cloud KMS encryption key that will be used to protect destination BigQuery table"
  type        = string
}
variable "routine_id" {
  description = "The ID of the the routine"
  type        = string
  default     = "routine_id01"
}
variable "job_id" {
  description = " The ID of the job"
  type        = string
  default     = "mmjob01"
}
*/

#OPTIONAL VARIABLES

variable "friendly_name" {
  description = "A descriptive name for the dataset"
  type        = string
  default     = "my_dataset"
}



variable "delete_contents_on_destroy" {
  description = "If set to true, delete all the tables in the dataset when destroying the resource; otherwise, destroying the resource will fail if tables are present"
  type        = bool
  default     = true
}

variable "default_table_expiration_ms" {
  description = "The default lifetime of all tables in the dataset, in milliseconds"
  type        = number
  default     = 3600000
}

variable "default_partition_expiration_ms" {
  description = "The default partition expiration for all partitioned tables in the dataset, in milliseconds"
  type        = number
  default     = 3600000
}



variable "table_id" {
  description = "The ID of the dataset containing this table"
  type        = string
  default     = "test_table"
}

variable "members" {
  description = "Identities that will be granted the privilege in role"
  type        = list(string)
  default     = ["allUsers"]
}

variable "routine_type" {
  description = "The type of routine"
  type        = string
  default     = "PROCEDURE"
}
variable "type" {
  description = "The supported types are DAY, HOUR, MONTH, and YEAR, which will generate one partition per day, hour, month, and year, respectively"
  type        = string
  default     = "DAY"
}
